<?php

require_once 'PHPUnit/Autoload.php';

require_once dirname(__FILE__) . '/../class.SqlGenerator.php';

/**
 * Test class for SqlGenerator.
 * Generated by PHPUnit on 2011-08-19 at 08:06:54.
 */
class SqlGeneratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SqlGenerator
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SqlGenerator;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    public function testSelect() {
        $exp = 'SELECT name,age FROM users;';
        $act = $this->object->select('name,age')->from('users')->getSql(true);
        
        $this->assertEquals($exp, $act);
    }


    public function testSelectAll() {
        $exp = 'SELECT * FROM users';
        $act = $this->object->select('*')->from('users')->getSql();
        
        $this->assertEquals($exp, $act);
    }


    public function testInsert() {
        $values = array(
            array('name' => 'Marcin', 'surname' => 'Kowalski', 'age' => 14),
            array('name' => 'Rafał', 'surname' => 'Nowak', 'age' => 19),
            array('name' => 'Stanisław', 'surname' => 'Adamczyk', 'age' => 33)
        );
        
        $exp = 'INSERT INTO users (name, surname, age) VALUES ("Marcin", "Kowalski", 14), ("Rafał", "Nowak", 19), ("Stanisław", "Adamczyk", 33)';
        $act = $this->object->insert($values)->into('users')->getSql();

        $this->assertEquals($exp, $act);
    }


    /**
     * @todo Implement testInto().
     */
    public function testInto() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testLimit().
     */
    public function testLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testAlterTable().
     */
    public function testAlterTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testTable().
     */
    public function testTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testTables().
     */
    public function testTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testWhere().
     */
    public function testWhere() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testAndSql().
     */
    public function testAndSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testOrSql().
     */
    public function testOrSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testLike().
     */
    public function testLike() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testIn().
     */
    public function testIn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testSetTables().
     */
    public function testSetTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testSetFields().
     */
    public function testSetFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testSetSql().
     */
    public function testSetSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testReset().
     */
    public function testReset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testFrom().
     */
    public function testFrom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testGetSql().
     */
    public function testGetSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testBuildDeleteSql().
     */
    public function testBuildDeleteSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement testGetSqlAction().
     */
    public function testGetSqlAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
